# Generated by Django 3.2.7 on 2021-10-01 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('km_por_galao', models.FloatField()),
                ('cilindros', models.IntegerField()),
                ('cavalor_de_forca', models.IntegerField()),
                ('peso', models.FloatField()),
                ('aceleracao', models.FloatField()),
                ('ano', models.DateField()),
                ('origem', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('origem', models.CharField(max_length=255)),
            ],
        ),
    ]
