# Generated by Django 3.2.7 on 2021-10-03 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marca',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='ma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('km_por_galao', models.FloatField()),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carros.marca')),
            ],
        ),
    ]
