# Generated by Django 3.2.7 on 2021-10-03 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0003_auto_20211003_1250'),
    ]

    operations = [
        migrations.CreateModel(
            name='Automovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('km_por_galao', models.FloatField()),
                ('cilindros', models.IntegerField()),
                ('cavalor_de_forca', models.IntegerField()),
                ('peso', models.FloatField()),
                ('aceleracao', models.FloatField()),
                ('ano', models.DateField()),
                ('origem', models.CharField(max_length=255)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carros.marca')),
            ],
        ),
    ]
