# Generated by Django 3.2.7 on 2021-10-03 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0004_automovel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carro',
        ),
    ]
