# Generated by Django 3.2.7 on 2021-10-03 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0005_delete_carro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automovel',
            name='marca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carros.marca'),
        ),
    ]
